version: '3'

services:
  delivery.api:
    image: delivery.api
    build:
      context: .
      dockerfile: src/Services/Delivery/Delivery.API/Dockerfile

  webmvc:
    image: webmvc
    build:
      context: .
      dockerfile: src/Web/MVC/WebMVC/Dockerfile


  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

